#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Appends every command to the history file once it is executed
setopt inc_append_history
# # Reloads the history whenever you use it
setopt share_history

# god awful python shit for ansible
source "${HOME}/virtualenvs/aws/bin/activate"

# k8s
source <(kubectl completion zsh)
source <(kops completion zsh)
source <(stern --completion zsh)
export KOPS_FEATURE_FLAGS="+DrainAndValidateRollingUpdate"
alias k='kubectl'
alias wp="watch -n1 'kubectl get pods -o wide'"
export HELM_CONFIG_HOME=/Users/erik.olson/repos/helm-config
# wp () {
#   GREP=${1:+"| grep $1"}
#   watch -n1 "kubectl get pods ${GREP}"
# }
ctx() {
  context=$1
  if [ -z "$context" ] ; then
    echo "USAGE: ctx <context-name>"
    echo "Available contexts:"
    kubectl config get-contexts
  else
    kubectl config use-context $context
  fi
}
kssh() {
  POD=$1
  NAMESPACE=${2:+"--namespace ${2}"}
  search_command="kubectl get pods $POD $NAMESPACE -o jsonpath='{.status.hostIP}'"
  ip=$(eval $search_command)
  if [ $? -ne '0' ] ; then
    echo "No hostIP found."
    return 1
  fi
  echo "ssh ${ip}"
  ssh $ip
}

adebug() { 
  docker run -it --rm --pid=container:$1 --net=container:$1 --cap-add sys_admin chriswayg/toolbox bash 
}
# GO DO STUFF
export GOPATH=$HOME/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export GOARCH=amd64
export GOOS=darwin

# AWS
export AWS_REGION=${AWS_REGION:-'us-east-1'}
source ~/.aws/aws_on.include
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# GCE
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/erik.olson/Downloads/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/erik.olson/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/erik.olson/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/erik.olson/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# set the DRONE_SERVER and DRONE_TOKEN
. ~/.drone

# github key
ssh-add ~/.ssh/erkolson.github.key

# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#CTRL-T to fuzzily search for a file or directory in your home directory then insert its path at the cursor
#ALT-C to fuzzily search for a directory in your home directory then cd into it
#CTRL-R to fuzzily search your command line history then run an old command
export FZF_DEFAULT_COMMAND="fd . $HOME"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -t d . $HOME"
export ANSIBLE_REPO=/Users/erik.olson/repos/devco-ansible

export PATH=$PATH:/Users/erik.olson/repos/elasticsearch-dump/bin

# rust
export PATH="$HOME/.cargo/bin":$PATH

source <(kubectl completion zsh)


