#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Appends every command to the history file once it is executed
setopt inc_append_history
# # Reloads the history whenever you use it
setopt share_history

source ~/devco/bin/activate
source <(kubectl completion zsh)

export GOPATH=$HOME/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export GOARCH=amd64
export GOOS=darwin

export AWS_REGION=${AWS_REGION:-'us-east-1'}
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export HELM_CONFIG_HOME=/Users/erik.olson/repos/helm-config

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/erik.olson/Downloads/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/erik.olson/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/erik.olson/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/erik.olson/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# k8s
alias ctx='kubectl config use-context'
alias k='kubectl'
alias wp='watch kubectl get pods'
kssh() {
  POD=$1
  ip=$(kubectl get pods $POD -o jsonpath='{.status.hostIP}')
  if [ $? -ne '0' ] ; then
    exit 1
  fi
  echo "ssh ${ip}"
  ssh $ip
}

# set the DRONE_SERVER and DRONE_TOKEN
. ~/.drone
